version: '3.9'
services:
  backend:
    build: .
    container_name: app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/data

  database_postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./pg_db:/docker-entrypoint-initdb.d

  rd_db:
    image: redis
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./rd_db:/data

volumes:
  database_postgres:
    driver: local
  database_redis:
    driver: local
