version: '3.9'
services:


  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg_db:/var/lib/postgresql


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    volumes:
      - ./pg_admin:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  database_postgres:
    driver: local
  database_redis:
    driver: local
