version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
  database_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default_database
    ports:
      - '5432:5432'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
volumes:
  database_postgres:
    driver: local


