version: '3.9'
services:
  backend:
    container_name: fast_api_app
    build: .
    volumes:
      - .:/FastAPIIntern
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg_db:/var/lib/postgresql

  rd_database:
    image: redis
    container_name: redis
    env_file:
      - ./.env
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./rd_db:/data
    command: [ "redis-server", "/data" ]

volumes:
  database_postgres:
    driver: local
  database_redis:
    driver: local
